### ISSUE TITLE
Link with fathom

### ISSUE THREAD

**Issue by sbusso** [astrocorp42/signal#1]
As the introduction is the same word for word, what is the link of this code base with [https://github.com/usefathom/fathom](https://github.com/usefathom/fathom) ?

BTW I prefer also Vue :)

**Comment by z0mbie42** [comment]
Hi, the introduction is the same because the goals seems to be aligned, there is no link because this projects does not share anything else with fathom, If you think there is a problem using fathom's introduction, I can change it whtin 5 hours
Best regards

**Comment by sbusso** [comment]
ok no big deal, i m not owner of fathom but as I m working on similar topic the similarities raised the question. Thanks.

**Comment by z0mbie42** [comment]
Profitez bien de Chiang Mai, j'aimerais y être en ces moments de vague de froid en France ;)
